package com.grayMatter.ExceptionHandling;

public class DemoOnExceptions {
public static void main(String[] args) {
	int num=7,deno=2;
  
	try{
		System.out.println(num/deno);
	}catch(ArithmeticException e) {
		
		System.out.println("Dviding By Zero");
		e.printStackTrace();
		System.out.println(e.getMessage());
	}catch(RuntimeException e)
	{
		System.out.println("Dviding By Zero");
		e.printStackTrace();
		System.out.println(e.getMessage());
	}
	
	System.out.println("End of main block");
	
}
}
